# carry over from pretraining yaml
app: fed_vjepa
folder: /content/vjepa2_federated/fed_training/fed_run/logs

meta:
  dtype: bfloat16
  use_sdpa: true

model:
  model_name: vit_small
  pred_depth: 6
  pred_embed_dim: 192
  pred_num_heads: 12
  uniform_power: true
  use_mask_tokens: true
  use_rope: true
  zero_init_mask_tokens: true

mask:
  - aspect_ratio: [0.75, 1.5]
    full_complement: false
    max_keep: null
    max_temporal_keep: 1.0
    num_blocks: 8
    spatial_scale: [0.15, 0.15]
    temporal_scale: [1.0, 1.0]
  - aspect_ratio: [0.75, 1.5]
    full_complement: false
    max_keep: null
    max_temporal_keep: 1.0
    num_blocks: 2
    spatial_scale: [0.7, 0.7]
    temporal_scale: [1.0, 1.0]

# federated-specific — new
num_rounds: 100
num_clients: 8
lora_r: 8
lora_alpha: 16.0

pretrain_checkpoint:
  pretrain_checkpoint: /content/vjepa2_federated/fed_training/latest.pt

data:
  dataset_type: VideoDataset
  dataset_type: VideoDataset
  client_datasets:
    - /content/vjepa2_federated/fed_training/client_epic_P01/videos.csv
    - /content/vjepa2_federated/fed_training/client_epic_P02/videos.csv
    - /content/vjepa2_federated/fed_training/client_bdd_00/videos.csv
    - /content/vjepa2_federated/fed_training/client_bdd_02/videos.csv
    - /content/vjepa2_federated/fed_training/client_hmdb_0/videos.csv
    - /content/vjepa2_federated/fed_training/client_hmdb_1/videos.csv
    - /content/vjepa2_federated/fed_training/client_hmdb_2/videos.csv
    - /content/vjepa2_federated/fed_training/client_hmdb_3/videos.csv
  client_datasets_path:
    - /content/vjepa2_federated/fed_training/client_epic_P01/
    - /content/vjepa2_federated/fed_training/client_epic_P02/
    - /content/vjepa2_federated/fed_training/client_bdd_00/
    - /content/vjepa2_federated/fed_training/client_bdd_02/
    - /content/vjepa2_federated/fed_training/client_hmdb_0/
    - /content/vjepa2_federated/fed_training/client_hmdb_1/
    - /content/vjepa2_federated/fed_training/client_hmdb_2/
    - /content/vjepa2_federated/fed_training/client_hmdb_3/
  batch_size: 16
  crop_size: 224
  patch_size: 16
  dataset_fpcs:
    - 16
  tubelet_size: 2
  fps: 4
  num_workers: 8
  pin_mem: True
  persistent_workers: True

federated:
  save_dir: /content/vjepa2_federated/fed_training/fed_run
  resume_checkpoint: /content/vjepa2_federated/fed_training/fed_run/fed_latest.pt
  save_every: 10
  local_steps: 50
  lr: 1.0e-4
  weight_decay: 0.04
  loss_exp: 1.0
  ema: [0.996, 1.0]